logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    fr.codecake.boilerplate: INFO

spring:
  application:
    name: Codecake backend boilerplate
  threads:
    virtual:
      enabled: true
  datasource:
    hikari:
      poolName: Hikari
      auto-commit: false
    password: ''
    driver-class-name: org.postgresql.Driver
    username: codecake
    url: jdbc:postgresql://localhost:5432/boilerplate
    type: com.zaxxer.hikari.HikariDataSource
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          batch_size: 25
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
        generate_statistics: false
        order_updates: true
        connection:
          provider_disables_autocommit: true
        order_inserts: true
        default_schema: public
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/master.xml
  #    drop-first: true
  security:
    oauth2:
      client:
        registration:
          oidc:
            client-secret: <client-secret>
            client-id: <client-id>
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          oidc:
            issuer-uri: <domain-name>
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

server:
  port: 8080

application:
  security:
    oauth2:
      audience: <api-url>
